services:
  - type: web
    name: cashflow-game
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm install
    startCommand: node server/server.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false   # Render dashboard dan qo'lda kiritiladi
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: SUPERADMIN_USERNAME
        value: superadmin
      - key: SUPERADMIN_EMAIL
        value: superadmin@example.com
      - key: SUPERADMIN_PASSWORD
        value: yourSuperSecretAdminPass
      - key: MAX_PLAYERS_PER_ROOM
        value: 6
      - key: MIN_PLAYERS_TO_START
        value: 2
      - key: STARTING_BALANCE
        value: 3000
      - key: LOG_LEVEL
        value: info
